Bootstrap: docker
From: ubuntu:18.04

%setup
mkdir -p ${SINGULARITY_ROOTFS}/src/augment
mkdir -p ${SINGULARITY_ROOTFS}/src/numcodecs
mkdir -p ${SINGULARITY_ROOTFS}/src/zarr
mkdir -p ${SINGULARITY_ROOTFS}/src/gunpowder
mkdir -p ${SINGULARITY_ROOTFS}/src/daisy
mkdir -p ${SINGULARITY_ROOTFS}/src/funlib
mkdir -p ${SINGULARITY_ROOTFS}/src/neurolight

%labels
maintainer funkej@janelia.hhmi.org

%post

# basic ubuntu packages

apt update
apt install -y --no-install-recommends \
build-essential \
ca-certificates \
cmake \
git \
libmlpack-dev \
liblzma-dev \
wget && \
rm -rf /var/lib/apt/lists/*

# install conda

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p /miniconda
PATH="/miniconda/bin:$PATH"
conda config --set always_yes yes --set changeps1 no
conda update -q conda
conda info -a
conda install python=3.6

# install tensorflow

conda install tensorflow-gpu
# conda install tensorflow-gpu
conda info -a

# install z5py
conda install -c conda-forge z5py

# dependencies for mouselight

pip install cython

AUGMENT_ROOT=/src/augment
AUGMENT_REPOSITORY=https://github.com/funkey/augment.git
AUGMENT_REVISION=4a42b01ccad7607b47a1096e904220729dbcb80a

cd ${AUGMENT_ROOT}
git clone ${AUGMENT_REPOSITORY} . && \
git checkout ${AUGMENT_REVISION}
pip install -r requirements.txt
PYTHONPATH=${AUGMENT_ROOT}:$PYTHONPATH

NUMCODECS_ROOT=/src/numcodecs
NUMCODECS_REPOSITORY=https://github.com/funkey/numcodecs
NUMCODECS_REVISION=f950047d7b666723f81006cbdfd82c0e6705c39c

cd ${NUMCODECS_ROOT}
git clone ${NUMCODECS_REPOSITORY} . && \
git checkout ${NUMCODECS_REVISION} && \
git submodule update --init --recursive
pip install -r requirements.txt
python setup.py install

ZARR_ROOT=/src/zarr
ZARR_REPOSITORY=https://github.com/funkey/zarr
ZARR_REVISION=9ddf849a6e3329f5ff361ebf6156712926e2fdfe

cd ${ZARR_ROOT}
git clone ${ZARR_REPOSITORY} . && \
git checkout ${ZARR_REVISION}
pip install -r requirements.txt
python setup.py install

# GUNPOWDER_ROOT=/src/gunpowder
# GUNPOWDER_REPOSITORY=https://github.com/pattonw/gunpowder
# GUNPOWDER_REVISION=0107124398757a4bbb725d15531b7c2b6e10ad17
# 
# cd ${GUNPOWDER_ROOT}
# git clone ${GUNPOWDER_REPOSITORY} . && \
# git checkout ${GUNPOWDER_REVISION}
# pip install -r requirements.txt
# python setup.py build_ext --inplace
# PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH

DAISY_ROOT=/src/daisy
DAISY_REPOSITORY=https://github.com/funkelab/daisy
DAISY_REVISION=4b3fdd4d4c1360f01dab8fb6a0c82f60d7b1a209

cd ${DAISY_ROOT}
git clone ${DAISY_REPOSITORY} . && \
git checkout ${DAISY_REVISION}
pip install -r requirements.txt
python setup.py build_ext --inplace
PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH

FUNLIB_ROOT=/src/funlib
FUNLIB_REPOSITORY=https://github.com/funkelab/funlib.learn.tensorflow
FUNLIB_REVISION=5d6313a980b7dc6ff7aed0bec873245c125c4e0d

cd ${FUNLIB_ROOT}
git clone ${FUNLIB_REPOSITORY} . && \
git checkout ${FUNLIB_REVISION}
pip install -r requirements.txt
python setup.py build_ext --inplace
PYTHONPATH=${FUNLIB_ROOT}:$PYTHONPATH

# Install neurolight locally, that way I don't need to rebuild
# this container every time I change something
# NEUROLIGHT_ROOT=/src/neurolight
# NEUROLIGHT_REPOSITORY=https://github.com/pattonw/neurolight
# NEUROLIGHT_REVISION=f6bfb12c9d9ebecca47f32372f075ef3c88800b3
# 
# cd ${NEUROLIGHT_ROOT}
# git clone ${NEUROLIGHT_REPOSITORY} . && \
# git checkout ${NEUROLIGHT_REVISION}
# pip install -r requirements.txt
# python setup.py build_ext --inplace
# PYTHONPATH=${NEUROLIGHT_ROOT}:$PYTHONPATH

pip install mahotas
pip install pymongo

%environment
export AUGMENT_ROOT=/src/augment
export PYTHONPATH=${AUGMENT_ROOT}:$PYTHONPATH
export GUNPOWDER_ROOT=/src/gunpowder
export PYTHONPATH=${GUNPOWDER_ROOT}:$PYTHONPATH
export DAISY_ROOT=/src/daisy
export PYTHONPATH=${DAISY_ROOT}:$PYTHONPATH
export FUNLIB_ROOT=/src/funlib
export PYTHONPATH=${FUNLIB_ROOT}:$PYTHONPATH
export NEUROLIGHT_ROOT=/src/neurolight
export PYTHONPATH=${NEUROLIGHT_ROOT}:$PYTHONPATH
export PATH=/miniconda/bin:${PATH}

# disable threads for numpy and the like, they get into our way when we
# pre-fetch batches using multiple processes
export OMP_NUM_THREADS=1

%runscript
exec /bin/bash "$@"
